config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login',to: 'sessions#new'
  post 'login',to:'sessions#create'
  delete 'logout',to:'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username,presence: true,uniqueness: true,
            uniqueness: { case_sensitive: false },
            length:{minimum:4,maximum:15}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user,:logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger]= "you must logged in to use this action"
      redirect_to root_path
    end
  end
  
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
      @messages=Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
     @user=User.new
  end

  def create
    user=User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      flash.now[:success]= "You have successfully logged in."
      session[:user_id]=user.id
      redirect_to root_path
    else
      flash[:error]="Incorrect credentials! Try again"
      render 'new'
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:success]="You have successfully logged out"
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="  circular coffee orange icon"></i>
  ChatRoom
</h2>
<div class="ui two column grid ">
  <div class="twelve wide column">
    <div class="ui card fluid raised card chatbox">
      <div class="content">
        <div class="ui  feed">
          <div class="event">
            <div class="content">

              <div class="summary">
                <%=render @messages %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="extra content">
        <div class="fourteen wide column">
          <form class="ui reply form">
          <div class="field">
            <div class="ui fluid icon input">
              <input type="text" placeholder="Enter a message....">
              <i class="bordered  orange icon  inverted  edit icon"></i>
            </div>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>


  <div class="four wide column">
    <div class="ui card fluid raised card chatbox">
      <div class="content">
        <div class="ui vertical pointing menu inverted">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
      <%=link_to 'Chatroom',root_path,class:"item"%>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if !logged_in? %>
          <%= link_to 'Login', login_path,class:"item" %>
          <% end %>
          <% if logged_in? %>
          <%= link_to 'Logout',logout_path,method: :delete,class:"item" %>
          <% end %>
        </div>
      </div>
      <div class="item">
        <%=link_to 'Login',login_path,class:"ui  primary button"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%=render 'layouts/navigation' %>
  <body>
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<p><em><%=message.user.username%>:-</em> <%=message.body%></p>